### ISSUE TITLE
HTTP 500 when trying to authenticate via Facebook on heroku

### ISSUE THREAD

**Issue by pirj** [nov/rack-oauth2-sample#1]
rack-oauth2-sample.heroku.com

**Comment by nov** [comment]
Is it still happening?
If so, it's because your browser can't get facebook's cookie.
Enabling 3rd party cookie might help.

**Comment by pirj** [comment]
Still happening. What might cause http 500 on http://rack-oauth2-sample.heroku.com/session/new ?
"We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly."

**Comment by nov** [comment]
Maybe it's browser issue.
Which browser's which version do you use?

**Comment by pirj** [comment]
Seems to be browser specific. Safari 3.1

**Comment by nov** [comment]
Safari 3!?
Use newer browser.

**Comment by pirj** [comment]
What's wrong with safari 3? It can HTML5 etc.
BTW OmniAuth worked like a charm.

**Comment by nov** [comment]
Ah, you mean Safari5?

**Comment by pirj** [comment]
No, I really mean Safari 3. According to Wikipedia, there's nothing new in 4 and 5 except for new JS engine, HTML5 video support. From my personal experience S3 also lacks some SSL encryption option support. It's pretty outdated by I wouldn't compare it to IE6. Anyway no idea why this issue may occur.
But yes, you're right, it's only 0.20% of browser market share and only 5% amongst all Safari versions, so don't bother.
