### ISSUE TITLE
Facebook login error - given URL is not allowed by the Application configuration

### ISSUE THREAD

**Issue by codyaray** [nov/rack-oauth2-sample#10]
When clicking the Facebook login button on the home page of the app (running locally), the Facebook modal pops up with the following message highlighted in red:

"Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

My guess is that "localhost:3000" has been removed from the App's settings for this development client_id/client_secret in the facebook config. Can this be restored so users don't have to create a new facebook app just to test this locally?

**Comment by nov** [comment]
Modify `config/facebook.yml` as you needed
