### ISSUE TITLE
TypeError in Accounts#new

### ISSUE THREAD

**Issue by itsmechlark** [nov/rack-oauth2-sample#11]
<pre><code>
application.html.erb where line #8 raised
no implicit conversion of nil into String
</code></pre>

<b>Trace</b>

<pre><code>
actionpack (3.0.20) lib/action_view/helpers/asset_tag_helper.rb:749:in `start_with?'
actionpack (3.0.20) lib/action_view/helpers/asset_tag_helper.rb:749:in `compute_public_path'
actionpack (3.0.20) lib/action_view/helpers/asset_tag_helper.rb:424:in `stylesheet_path'
actionpack (3.0.20) lib/action_view/helpers/asset_tag_helper.rb:830:in `stylesheet_tag'
actionpack (3.0.20) lib/action_view/helpers/asset_tag_helper.rb:513:in `block in stylesheet_link_tag'
actionpack (3.0.20) lib/action_view/helpers/asset_tag_helper.rb:513:in `collect'
actionpack (3.0.20) lib/action_view/helpers/asset_tag_helper.rb:513:in `stylesheet_link_tag'
app/views/layouts/application.html.erb:8:in `_app_views_layouts_application_html_erb___943741427_20004792__931848670'
actionpack (3.0.20) lib/action_view/template.rb:135:in `block in render'
activesupport (3.0.20) lib/active_support/notifications.rb:54:in `instrument'
actionpack (3.0.20) lib/action_view/template.rb:127:in `render'
actionpack (3.0.20) lib/action_view/render/layouts.rb:80:in `_render_layout'
actionpack (3.0.20) lib/action_view/render/rendering.rb:62:in `block in _render_template'
activesupport (3.0.20) lib/active_support/notifications.rb:52:in `block in instrument'
activesupport (3.0.20) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.0.20) lib/active_support/notifications.rb:52:in `instrument'
actionpack (3.0.20) lib/action_view/render/rendering.rb:56:in `_render_template'
actionpack (3.0.20) lib/action_view/render/rendering.rb:26:in `render'
actionpack (3.0.20) lib/abstract_controller/rendering.rb:115:in `_render_template'
actionpack (3.0.20) lib/abstract_controller/rendering.rb:109:in `render_to_body'
actionpack (3.0.20) lib/action_controller/metal/renderers.rb:47:in `render_to_body'
actionpack (3.0.20) lib/action_controller/metal/compatibility.rb:55:in `render_to_body'
actionpack (3.0.20) lib/abstract_controller/rendering.rb:102:in `render_to_string'
actionpack (3.0.20) lib/abstract_controller/rendering.rb:93:in `render'
actionpack (3.0.20) lib/action_controller/metal/rendering.rb:17:in `render'
actionpack (3.0.20) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.0.20) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
D:/itsmechlark/Ruby200/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
activesupport (3.0.20) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.0.20) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.0.20) lib/action_controller/metal/instrumentation.rb:78:in `cleanup_view_runtime'
activerecord (3.0.20) lib/active_record/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
actionpack (3.0.20) lib/action_controller/metal/instrumentation.rb:39:in `render'
actionpack (3.0.20) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (3.0.20) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (3.0.20) lib/abstract_controller/base.rb:150:in `process_action'
actionpack (3.0.20) lib/action_controller/metal/rendering.rb:11:in `process_action'
actionpack (3.0.20) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.0.20) lib/active_support/callbacks.rb:436:in `_run__164525982__process_action__644413431__callbacks'
activesupport (3.0.20) lib/active_support/callbacks.rb:410:in `_run_process_action_callbacks'
activesupport (3.0.20) lib/active_support/callbacks.rb:94:in `run_callbacks'
actionpack (3.0.20) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.0.20) lib/action_controller/metal/rescue.rb:17:in `process_action'
actionpack (3.0.20) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.0.20) lib/active_support/notifications.rb:52:in `block in instrument'
activesupport (3.0.20) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.0.20) lib/active_support/notifications.rb:52:in `instrument'
actionpack (3.0.20) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.0.20) lib/abstract_controller/base.rb:119:in `process'
actionpack (3.0.20) lib/abstract_controller/rendering.rb:41:in `process'
actionpack (3.0.20) lib/action_controller/metal.rb:138:in `dispatch'
actionpack (3.0.20) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.0.20) lib/action_controller/metal.rb:178:in `block in action'
actionpack (3.0.20) lib/action_dispatch/routing/route_set.rb:68:in `call'
actionpack (3.0.20) lib/action_dispatch/routing/route_set.rb:68:in `dispatch'
actionpack (3.0.20) lib/action_dispatch/routing/route_set.rb:33:in `call'
rack-mount (0.6.14) lib/rack/mount/route_set.rb:148:in `block in call'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:93:in `block in recognize'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:89:in `optimized_each'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:92:in `recognize'
rack-mount (0.6.14) lib/rack/mount/route_set.rb:139:in `call'
actionpack (3.0.20) lib/action_dispatch/routing/route_set.rb:499:in `call'
rack-oauth2 (1.0.0) lib/rack/oauth2/server/resource.rb:20:in `call'
rack-oauth2 (1.0.0) lib/rack/oauth2/server/resource/bearer.rb:8:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/head.rb:14:in `call'
rack (1.2.7) lib/rack/methodoverride.rb:24:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/flash.rb:182:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/cookies.rb:302:in `call'
activerecord (3.0.20) lib/active_record/query_cache.rb:32:in `block in call'
activerecord (3.0.20) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
activerecord (3.0.20) lib/active_record/query_cache.rb:12:in `cache'
activerecord (3.0.20) lib/active_record/query_cache.rb:31:in `call'
activerecord (3.0.20) lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/callbacks.rb:46:in `block in call'
activesupport (3.0.20) lib/active_support/callbacks.rb:416:in `_run_call_callbacks'
actionpack (3.0.20) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
rack (1.2.7) lib/rack/sendfile.rb:106:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
railties (3.0.20) lib/rails/rack/logger.rb:13:in `call'
rack (1.2.7) lib/rack/runtime.rb:17:in `call'
activesupport (3.0.20) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.2.7) lib/rack/lock.rb:13:in `block in call'
rack (1.2.7) lib/rack/lock.rb:13:in `synchronize'
rack (1.2.7) lib/rack/lock.rb:13:in `call'
actionpack (3.0.20) lib/action_dispatch/middleware/static.rb:30:in `call'
railties (3.0.20) lib/rails/application.rb:168:in `call'
railties (3.0.20) lib/rails/application.rb:77:in `method_missing'
railties (3.0.20) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.2.7) lib/rack/content_length.rb:13:in `call'
rack (1.2.7) lib/rack/handler/webrick.rb:52:in `service'
D:/itsmechlark/Ruby200/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
D:/itsmechlark/Ruby200/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
D:/itsmechlark/Ruby200/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
</code></pre>

**Comment by alexandru-calinoiu** [comment]
I've fixed this by removing `<%= stylesheet_link_tag :all %>` and `<%= javascript_include_tag :defaults %>` because there is no assets folder with default js and css
