### ISSUE TITLE
`request.env[Rack::OAuth2::Server::Resource::ACCESS_TOKEN]` is not passed?

### ISSUE THREAD

**Issue by pjammer** [nov/rack-oauth2-sample#2]
`request.env[Rack::OAuth2::Server::Resource::ACCESS_TOKEN]` is not passed, but `params[:oauth_token]` is?

``` ruby
 def require_oauth_token

      Rails.logger.debug "* In req  oauth token *: #{request.env[Rack::OAuth2::Server::Resource::ACCESS_TOKEN]} :: or :: #{params[:oauth_token]}"
      @current_token = AccessToken.find_by_token params[:oauth_token] #request.env[Rack::OAuth2::Server::Resource::ACCESS_TOKEN]

      Rails.logger.debug "** Here : #{@current_token} **"
      @current_token
      raise Rack::OAuth2::Server::Resource::Bearer::Unauthorized unless @current_token
    end
```

This code comes from authentication.rb, i added the debug statements obv.

Here is my rake middleware call:

use ActionDispatch::Static
use Rack::Lock
use ActiveSupport::Cache::Strategy::LocalCache
use Rack::Runtime
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::RemoteIp
use Rack::Sendfile
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::MethodOverride
use ActionDispatch::Head
use ActionDispatch::BestStandardsSupport
use Warden::Manager
use Rack::OAuth2::Server::Resource::Bearer
run FancyPants::Application.routes

Shouldn't i be getting that Access token as it was meant to be written, rather then passing params to it?

**Comment by nov** [comment]
None of current OAuth 2.0 token types uses <code>params[:oauth_token]</code>.
Bearer uses <code>bearer_token</code> and MAC supports only Authorization header.

**Comment by pjammer** [comment]
hmm, so why is omniauth sending params[:oauth_token] i wonder...

**Comment by nov** [comment]
It uses old OAuth2 spec.

**Comment by pjammer** [comment]
Hmm, so I have to update omniauth to send via this new spec, do you think?

Or should I use your gem as the consumer too, and just  screw using omniauth all together?

**Comment by nov** [comment]
What do you expect for omniauth?
It's just for authentication, non?

**Comment by pjammer** [comment]
Omniauth automagically sends back the params[:oauth_token].

I'd expect it or the dependency gem oauth2 to send your gem the token however the spec is for accepting tokens, i guess through the Headers.

Am I looking in the wrong spot for this, as i didn't code it in my app, so i assume omniauth is the one actually sending the params to my provider app.

**Comment by pjammer** [comment]
Oh, wait a minute, i think it is a url i sent my process to, to get User info.... somehow i have to get that params to follow the new spec. thanks

**Comment by nov** [comment]
Are you developing OAuth2 server or client?
If server, I recommend you to learn OAuth2 spec first.
If client, you don't need to care about rack-oauth2 gem for now.

FYI:
OAuth2 gem currently supports OAuth 2.0 draft v10.
It uses <code>oauth_token=xxx</code> in query/body and <code>Authorizations: OAuth xxx</code> in header.
http://tools.ietf.org/html/draft-ietf-oauth-v2-10
Rack::OAuth2 currently supports OAuth 2.0 draft v15.
It doesn't say anything about resource access and let other spec define the way.
http://tools.ietf.org/html/draft-ietf-oauth-v2-15

**Comment by pjammer** [comment]
I'm doing both.  I have a provider and another app that is consuming that provider's user data for authentication.

I've read through but it takes time to sink in, as you know.

However if they are specs to standardize oauth, then one would assume that the gem would follow it and there would really only be one way to do something.  Hence streamlining the process so it's easy for those implementing.  It just does a guy's head in right now is all, lol.

I appreciate your work of course, that wasn't a shot at you.  It's just that a gem should be drop in, add some config and go onto the the next section of the app, especially when it's all about standardizing like Oauth is for.

**Comment by nov** [comment]
If you do both, learning the spec is the fastest way.

**Comment by pjammer** [comment]
Ok, thanks again. http://tools.ietf.org/html/draft-ietf-oauth-v2-15#section-7 has interacting with protected resources.  I just have to figure out how to make uri or cgi (on of them, uri i think) send that authorization header with the Bearer token in it and I'm golden.

Thanks.

**Comment by pjammer** [comment]
To make your sample code work with Omniauth, for now, i had to do the following on line 41 of my authentication.rb file in lib/oauth2

``` ruby
def require_oauth_token
      @current_token = AccessToken.find_by_token(request.env["HTTP_AUTHORIZATION"].gsub(/OAuth /, ''))
....
```

Seems that this is how they pass the authorization from omniauth.
