### ISSUE TITLE
How to use the rack-oauth2-sample server

### ISSUE THREAD

**Issue by zhangyuxiu** [nov/rack-oauth2-sample#7]
I have started the server by using the command "rails server". When I input "http://localhost:3000" into the address bar, the browse runs successfully. 
Then I see a method "new" in class "AccountsController" in file "app/controllers/accounts_controller.rb", so  I input "http://localhost:3000/accounts/new" into the address bar to test the function. But I got the error: ActionController::RoutingError (No route matches "/accounts/new"):

Rendered /usr/lib/ruby/gems/1.8/gems/actionpack-3.0.10/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (7.9ms)

What's the problem?

I'm looking forward to your reply.
Thanks.

**Comment by nov** [comment]
you don't have such routes.
read routes.rb
