### ISSUE TITLE
How to use the client sample?

### ISSUE THREAD

**Issue by zhangyuxiu** [nov/rack-oauth2-sample#8]
https://gist.github.com/862393
I don't know how to use and test the client sample. In order to exec the example above, I must have the consts: YOUR_CLIENT_ID,YOUR_CLIENT_SECRET and so on. But where should I register and get the values?

I am looking forward to your reply.
Thanks!

**Comment by nov** [comment]
1. login to the sample OAuth server (click FB login button)
2. click "new client" link and register you client

Then you get client_id and client_secret.

**Comment by zhangyuxiu** [comment]
1. When I login to the sample OAuth2 server, I can only choose "like" the application, or publish information to my facebook. But I can't find "new client" link to register my client.
2. If I have a facebook account ,Then I can login to the OAuth2 Sample server , publish information to my facebook. I feel that the OAuth2 Sample server is like a third-party application that can use my information on facebook. Am I right?
3. What are the OAuth2 server's functions on earth? 

I am looking forward to your reply.
Thanks.

**Comment by nov** [comment]
Hum$B!D(B it seems you should read the OAuth2 spec first$B!D(B
close #8

**Comment by zhangyuxiu** [comment]
OK.Then I'll learn the OAuth2 spec again.
But firstly,If you can tell me where the "new client" link is? I have logged into the OAuth2 Sample Server, but I can not find the link.

Thanks.

**Comment by nov** [comment]
it's on dashboard.
http://rack-oauth2-sample.heroku.com/dashboard

**Comment by zhangyuxiu** [comment]
I have registered a facebook account. But when I visit the link: http://rack-oauth2-sample.heroku.com/dashboard , it redirects me to " http://rack-oauth2-sample.heroku.com/ " . I login to the server,but I can never see "new client".

What's the problem? How can I create a client?

Thanks!

zhangyuxiu1990

From: Nov Matake
Date: 2012-12-03 15:42
To: nov/rack-oauth2-sample
CC: zhangyuxiu
Subject: Re: [rack-oauth2-sample] How to use the client sample? (#8)
it's on dashboard.
http://rack-oauth2-sample.heroku.com/dashboard

**Comment by nov** [comment]
You are not successfully logging in..

**Comment by zhangyuxiu** [comment]
The login process I have done:
1. http://rack-oauth2-sample.heroku.com
1. click the button: Log in
2. click the button: "登录" , and it redirects me to the following page:

I feel I have logged in successfully , don't I ?

Thanks!

zhangyuxiu1990

From: Nov Matake
Date: 2012-12-05 17:24
To: nov/rack-oauth2-sample
CC: zhangyuxiu
Subject: Re: [rack-oauth2-sample] How to use the client sample? (#8)
You are not successfully logging in..

**Comment by nov** [comment]
If you successfully logged-in, you should be on /dashboard.

nov

**Comment by pkaeding** [comment]
I must be missing something here, but I don't see any login button on http://rack-oauth2-sample.heroku.com/.  This is what I am seeing (Chrome on OS X):

![](https://dl.dropboxusercontent.com/s/olj4lwnl53fz5il/2014-08-04%20at%209.57%20PM%202x.png)
